version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nilnil
    - revive
    - staticcheck
    - unconvert
    - unused

  settings:
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: duplicated-imports
        - name: errorf
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: increment-decrement
        - name: range
        - name: receiver-naming
        - name: time-equal
        - name: var-declaration

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
